package xxhash

// Generated by gen/slide.go. DO NOT EDIT.

const slideLength = 127

// Handles length 0-127 bytes using sum slides.
func slide(b []byte) uint64 {
	// This function use sum slides, theses are straight unrolled pieces of code which compute hashes, with middle jumps.
	// Each do not contain any conditions to make them trivial for the CPU to parse and never cause any pipeline flushes after the first jump table.
	// We need 32 different slides to cover each offset into the 32 block size. The trailing 32 bytes are handled by their own slides which are shared and reused by the higher slides.
	// The trailing 32 bytes slides are reused for each offset. The CPUs we care about can always correctly read unconditional jumps without causing a pipeline flush.

	// This function is written more like an optimized assembly routine, except we trick the compiler into generating good code by generating the slide ourself.
	// Using the go compiler make the call overhead cheaper since it will use the unstable ABIInternal passing through registers.
	// They are also extremely effective when hashing multiple values of the same size back to back.
	// Assumptions of this strategy:
	// - All the state except b's array will be correctly register allocated.
	//   It probably generate unnecessary MOVs but the critical path includes LAT3 multiplies for each block, so there is plenty of time to dispatch renames.
	// - The compiler is basic block based and will do a good enough job at layout. This is true for some the go compiler, llvm and some of gcc.
	//   This means I make very liberal use of goto, they shouldn't be red as JMPs but abstract basic blocks links.

	// Setups variables here since go doesn't want use to do dangerous gotos.
	v1 := prime1
	v1 += prime2
	v2 := prime2
	v3 := uint64(0)
	v4 := prime1
	v4 = -v4
	h := prime5
	n := uint64(len(b))

	// Jump table to various positions in the slide, this setups proofs for bounds checks.
	// From then on it need to make sure to maintain constance in the length of b.
	switch len(b) {
	case 0:
		// Handle this appart because it can be completely folded.
		h += n
		h ^= h >> 33
		h *= prime2
		h ^= h >> 29
		h *= prime3
		h ^= h >> 32
		return h
	case 1:
		goto sz_1
	case 2:
		goto sz_2
	case 3:
		goto sz_3
	case 4:
		goto sz_4
	case 5:
		goto sz_5
	case 6:
		goto sz_6
	case 7:
		goto sz_7
	case 8:
		goto sz_8
	case 9:
		goto sz_9
	case 10:
		goto sz_10
	case 11:
		goto sz_11
	case 12:
		goto sz_12
	case 13:
		goto sz_13
	case 14:
		goto sz_14
	case 15:
		goto sz_15
	case 16:
		goto sz_16
	case 17:
		goto sz_17
	case 18:
		goto sz_18
	case 19:
		goto sz_19
	case 20:
		goto sz_20
	case 21:
		goto sz_21
	case 22:
		goto sz_22
	case 23:
		goto sz_23
	case 24:
		goto sz_24
	case 25:
		goto sz_25
	case 26:
		goto sz_26
	case 27:
		goto sz_27
	case 28:
		goto sz_28
	case 29:
		goto sz_29
	case 30:
		goto sz_30
	case 31:
		goto sz_31
	case 32:
		goto sz_32
	case 33:
		goto sz_33
	case 34:
		goto sz_34
	case 35:
		goto sz_35
	case 36:
		goto sz_36
	case 37:
		goto sz_37
	case 38:
		goto sz_38
	case 39:
		goto sz_39
	case 40:
		goto sz_40
	case 41:
		goto sz_41
	case 42:
		goto sz_42
	case 43:
		goto sz_43
	case 44:
		goto sz_44
	case 45:
		goto sz_45
	case 46:
		goto sz_46
	case 47:
		goto sz_47
	case 48:
		goto sz_48
	case 49:
		goto sz_49
	case 50:
		goto sz_50
	case 51:
		goto sz_51
	case 52:
		goto sz_52
	case 53:
		goto sz_53
	case 54:
		goto sz_54
	case 55:
		goto sz_55
	case 56:
		goto sz_56
	case 57:
		goto sz_57
	case 58:
		goto sz_58
	case 59:
		goto sz_59
	case 60:
		goto sz_60
	case 61:
		goto sz_61
	case 62:
		goto sz_62
	case 63:
		goto sz_63
	case 64:
		goto sz_64
	case 65:
		goto sz_65
	case 66:
		goto sz_66
	case 67:
		goto sz_67
	case 68:
		goto sz_68
	case 69:
		goto sz_69
	case 70:
		goto sz_70
	case 71:
		goto sz_71
	case 72:
		goto sz_72
	case 73:
		goto sz_73
	case 74:
		goto sz_74
	case 75:
		goto sz_75
	case 76:
		goto sz_76
	case 77:
		goto sz_77
	case 78:
		goto sz_78
	case 79:
		goto sz_79
	case 80:
		goto sz_80
	case 81:
		goto sz_81
	case 82:
		goto sz_82
	case 83:
		goto sz_83
	case 84:
		goto sz_84
	case 85:
		goto sz_85
	case 86:
		goto sz_86
	case 87:
		goto sz_87
	case 88:
		goto sz_88
	case 89:
		goto sz_89
	case 90:
		goto sz_90
	case 91:
		goto sz_91
	case 92:
		goto sz_92
	case 93:
		goto sz_93
	case 94:
		goto sz_94
	case 95:
		goto sz_95
	case 96:
		goto sz_96
	case 97:
		goto sz_97
	case 98:
		goto sz_98
	case 99:
		goto sz_99
	case 100:
		goto sz_100
	case 101:
		goto sz_101
	case 102:
		goto sz_102
	case 103:
		goto sz_103
	case 104:
		goto sz_104
	case 105:
		goto sz_105
	case 106:
		goto sz_106
	case 107:
		goto sz_107
	case 108:
		goto sz_108
	case 109:
		goto sz_109
	case 110:
		goto sz_110
	case 111:
		goto sz_111
	case 112:
		goto sz_112
	case 113:
		goto sz_113
	case 114:
		goto sz_114
	case 115:
		goto sz_115
	case 116:
		goto sz_116
	case 117:
		goto sz_117
	case 118:
		goto sz_118
	case 119:
		goto sz_119
	case 120:
		goto sz_120
	case 121:
		goto sz_121
	case 122:
		goto sz_122
	case 123:
		goto sz_123
	case 124:
		goto sz_124
	case 125:
		goto sz_125
	case 126:
		goto sz_126
	case 127:
		goto sz_127
	default:
		panic("unreachable; slide overflow")
	}

	// Theses are the main slides, they handle 32 bytes 4 × 8 bytes at a time using ILP.
sz_127:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_95:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_63:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_31:
	h += n
	goto sz_31l

sz_126:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_94:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_62:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_30:
	h += n
	goto sz_30l

sz_125:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_93:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_61:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_29:
	h += n
	goto sz_29l

sz_124:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_92:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_60:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_28:
	h += n
	goto sz_28l

sz_123:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_91:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_59:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_27:
	h += n
	goto sz_27l

sz_122:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_90:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_58:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_26:
	h += n
	goto sz_26l

sz_121:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_89:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_57:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_25:
	h += n
	goto sz_25l

sz_120:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_88:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_56:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_24:
	h += n
	goto sz_24l

sz_119:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_87:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_55:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_23:
	h += n
	goto sz_23l

sz_118:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_86:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_54:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_22:
	h += n
	goto sz_22l

sz_117:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_85:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_53:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_21:
	h += n
	goto sz_21l

sz_116:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_84:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_52:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_20:
	h += n
	goto sz_20l

sz_115:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_83:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_51:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_19:
	h += n
	goto sz_19l

sz_114:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_82:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_50:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_18:
	h += n
	goto sz_18l

sz_113:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_81:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_49:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_17:
	h += n
	goto sz_17l

sz_112:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_80:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_48:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_16:
	h += n
	goto sz_16l

sz_111:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_79:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_47:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_15:
	h += n
	goto sz_15l

sz_110:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_78:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_46:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_14:
	h += n
	goto sz_14l

sz_109:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_77:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_45:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_13:
	h += n
	goto sz_13l

sz_108:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_76:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_44:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_12:
	h += n
	goto sz_12l

sz_107:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_75:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_43:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_11:
	h += n
	goto sz_11l

sz_106:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_74:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_42:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_10:
	h += n
	goto sz_10l

sz_105:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_73:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_41:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_9:
	h += n
	goto sz_9l

sz_104:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_72:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_40:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_8:
	h += n
	goto sz_8l

sz_103:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_71:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_39:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_7:
	h += n
	goto sz_7l

sz_102:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_70:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_38:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_6:
	h += n
	goto sz_6l

sz_101:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_69:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_37:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_5:
	h += n
	goto sz_5l

sz_100:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_68:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_36:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_4:
	h += n
	goto sz_4l

sz_99:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_67:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_35:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_3:
	h += n
	goto sz_3l

sz_98:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_66:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_34:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_2:
	h += n
	goto sz_2l

sz_97:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_65:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_33:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

sz_1:
	h += n
	goto sz_1l

sz_96:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_64:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

sz_32:
	v1 = round(v1, u64(b[0:8]))
	v2 = round(v2, u64(b[8:16]))
	v3 = round(v3, u64(b[16:24]))
	v4 = round(v4, u64(b[24:32]))
	b = b[32:]

	h = rol1(v1) + rol7(v2) + rol12(v3) + rol18(v4)
	h = mergeRound(h, v1)
	h = mergeRound(h, v2)
	h = mergeRound(h, v3)
	h = mergeRound(h, v4)

	h += n
	goto sz_0l

	// Theses are 8 bytes block trailing slides.
sz_31l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

sz_23l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

sz_15l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

goto sz_7l

sz_30l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

sz_22l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

sz_14l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

goto sz_6l

sz_29l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

sz_21l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

sz_13l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

goto sz_5l

sz_28l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

sz_20l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

sz_12l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

goto sz_4l

sz_27l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

sz_19l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

sz_11l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

goto sz_3l

sz_26l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

sz_18l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

sz_10l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

goto sz_2l

sz_25l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

sz_17l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

sz_9l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

goto sz_1l

sz_24l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

sz_16l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

sz_8l:
	h ^= round(0, u64(b[0:8]))
	h = rol27(h)*prime1 + prime4
	b = b[8:]

goto sz_0l

	// Theses are the 4 bytes trailing slides.
sz_7l:
	h ^= uint64(u32(b[:4])) * prime1
	h = rol23(h)*prime2 + prime3
	b = b[4:]
	goto sz_3l

sz_6l:
	h ^= uint64(u32(b[:4])) * prime1
	h = rol23(h)*prime2 + prime3
	b = b[4:]
	goto sz_2l

sz_5l:
	h ^= uint64(u32(b[:4])) * prime1
	h = rol23(h)*prime2 + prime3
	b = b[4:]
	goto sz_1l

sz_4l:
	h ^= uint64(u32(b[:4])) * prime1
	h = rol23(h)*prime2 + prime3
	b = b[4:]
	goto sz_0l

	// This is the 1 bytes trailing slide.
sz_3l:
	h ^= uint64(b[0]) * prime5
	h = rol11(h) * prime1
	b = b[1:]

sz_2l:
	h ^= uint64(b[0]) * prime5
	h = rol11(h) * prime1
	b = b[1:]

sz_1l:
	h ^= uint64(b[0]) * prime5
	h = rol11(h) * prime1
	b = b[1:]

	// Finally the terminator.
sz_0l:
	h ^= h >> 33
	h *= prime2
	h ^= h >> 29
	h *= prime3
	h ^= h >> 32

	return h
}
